### ISSUE TITLE
Supervisor Name - Maximo Work Orders

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#360]
What is needed to update the supervisor name in the domain lookup table and what are the implications with the Field Tool. Does this have to be a one-to-one relationship? There can now be multiple supervisors in one district. @cstevenson1 If there is anything additional or I misunderstood the question, please elaborate below.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Could you elaborate on this?

- Where is this field displayed in the Field Tool?
- Does this affect any reports? 
- Do the additional supervisors need to show up anywhere in the viewer?

**Comment by cstevenson1** [comment]
@KCI-Ablowers 

- It shows on the first page of the work order tab in the field tool (Structures/Conveyances since BMP Work orders are not in the field tool).

![image](https://user-images.githubusercontent.com/16919898/62867107-7d284c80-bce0-11e9-8998-b7d7bd169c06.png)

- Yes it impacts the work order section for Structure/Conveyance Reports.
![image](https://user-images.githubusercontent.com/16919898/62867281-f031c300-bce0-11e9-9cce-3fd73b50c1dc.png)

- Yes, it needs to show up in two places in the work orders tab in the viewer.
![image](https://user-images.githubusercontent.com/16919898/62867329-093a7400-bce1-11e9-8e38-80d7abe4cdd6.png)

![image](https://user-images.githubusercontent.com/16919898/62867365-1c4d4400-bce1-11e9-99fb-6f0ec788f243.png)

**Comment by KCI-Ablowers** [comment]
**Clarified with @cstevenson1 8/19/19**

Currently, the district supervisor is located in a lookup table, with no relationships. The structure of the table is detailed in the screenshot below- 

![image](https://user-images.githubusercontent.com/35460336/63275642-e3c4e180-c26f-11e9-9709-6bbf52717b9d.png)

**Comment by cstevenson1** [comment]
@KCI-Ablowers Any status update/answers on this item? Work orders are currently being updated with the wrong supervisor. The snip below shows the changes in personnel.

![image](https://user-images.githubusercontent.com/16919898/64610788-085b3780-d39e-11e9-9107-b5a6a3ef55fb.png)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 and I spoke on this issue today. 

- Values in the screenshot below and in the `deldot_migration2.DBO.LU_DISTRICT_SUPERVISORS` table in dev/prod.
https://user-images.githubusercontent.com/16919898/62867107-7d284c80-bce0-11e9-8998-b7d7bd169c06.png
- The new values are in the screenshot below.
https://user-images.githubusercontent.com/16919898/64610788-085b3780-d39e-11e9-9107-b5a6a3ef55fb.png
- @kanglu666, are these values populated in the Work Order via an overlay or a look-up? There is no relationship between the Work Order and Supervisor
- @kanglu666 If it is based on a look-up, can we update the table to allow for the selection of the supervisor? Then, KCI Newark(WR) can update the look-up table as needed and have that available in the field tool once rec/posted?

**Comment by KCI-Ablowers** [comment]
@kanglu666 Please do the following:

- Make the necessary updates to the field tool to allow a user to select the **supervisor** after selecting a **district**
- Use the table in the attached zipped GDB to replace the values currently in the database
[Updated_Supervisor_Table.zip](https://github.com/leeensminger/DelDOT-NPDES-Field-Tool/files/3596929/Updated_Supervisor_Table.zip)
- Reassign to @cstevenson1 when the new field tool version is released.

**Comment by cstevenson1** [comment]
@KCI-Ablowers supervisors were updated in database and field tool. Will confirm tomorrow after nightly script but I do not foresee any problems

![image](https://user-images.githubusercontent.com/16919898/64722209-02e41700-d49c-11e9-86ae-c2ae14889cf1.png)

**Comment by kanglu666** [comment]
fixed in  dev version 8.2

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Can you verify that this is correct now in v8.2?

**Comment by cstevenson1** [comment]
@KCI-Ablowers Something is still not correct. Jeff Trent is a supervisor for Canal and in the snip below, he is the only option for South District. This was not observed on the first work order created. The issue seems to arise when a different district than where the feature is located is used on subsequent work orders. This is a legitimate workflow because we have features that are physically located in Canal District but DelDOT has assigned responsibility of those features to North District. 

![image](https://user-images.githubusercontent.com/16919898/65042892-db6fcd00-d927-11e9-8aa3-ca136cd72e4b.png)

**Comment by kanglu666** [comment]
updated, ready for testing in dev version 8.3

**Comment by KCI-Ablowers** [comment]
@cstevenson1 please test when time allows.

**Comment by cstevenson1** [comment]
@KCI-Ablowers seems fine now in Dev Field Tool v8.3. I will confirm in database tomorrow after nightly script.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I will leave this unconfirmed until you check the DB tomorrow.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Have you had a chance to confirm this issue?

**Comment by cstevenson1** [comment]
values came through in nightly script. push to prod
![image](https://user-images.githubusercontent.com/16919898/65766930-60ae6b00-e0fa-11e9-95e2-9394c4b01485.png)

**Comment by KCI-Ablowers** [comment]
Confirmed by @cstevenson1. Push to Prod - Confirmed.

**Comment by kanglu666** [comment]
ready for PROD 8.3 release

**Comment by cstevenson1** [comment]
confirmed in PROD
