### ISSUE TITLE
Field Tool Crash 

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#91]
I created a new inlet and saved the structure after entering location and inventory information. I then created a new inspection and filled out each page of the form as shown in the photos below. I then saved the inspection with no issues. I hit cancel to return to the list of inspections as I had been doing for other inspections but when I clicked the green check mark to try and reopen the inspection, the field tool crashed. The only major difference between this inspection and others (that I know of) was backdating the inspection date. I clicked the calendar and chose a date from December 2015 for the inspection date on the first page of the inspection form. 

1. 

![image](https://cloud.githubusercontent.com/assets/16919898/13011422/baae9c5e-d174-11e5-983f-467b9d4626d5.png)

2.
![image](https://cloud.githubusercontent.com/assets/16919898/13011429/c00861ee-d174-11e5-98e0-2746d9819e87.png)

3.
![image](https://cloud.githubusercontent.com/assets/16919898/13011435/c8f6e5be-d174-11e5-88de-8a8dffc14b8c.png)

4.
![image](https://cloud.githubusercontent.com/assets/16919898/13011441/d015ad6c-d174-11e5-8f6e-7e83e834f29f.png)

5.
![image](https://cloud.githubusercontent.com/assets/16919898/13011459/dea8e3bc-d174-11e5-8437-f07b0865ef36.png)

Result:
![image](https://cloud.githubusercontent.com/assets/16919898/13011583/70e75c7c-d175-11e5-9d3b-3c4d6850c1f7.png)

**Comment by kanglu666** [comment]
fixed, ready for testing in next release

**Comment by cstevenson1** [comment]
The field tool does not crash anymore but when I tried to reopen the inspection, the date had been changed to the current date (it does not keep the backdated date).


![image](https://cloud.githubusercontent.com/assets/16919898/13926469/d58ee3f6-ef62-11e5-85a2-b749196bf98e.png)

![image](https://cloud.githubusercontent.com/assets/16919898/13926539/2d5196ce-ef63-11e5-87db-6493897587d3.png)

![image](https://cloud.githubusercontent.com/assets/16919898/13926643/a9b33eac-ef63-11e5-9427-96c58f61cd38.png)

**Comment by kanglu666** [comment]
fixed, ready for testing in next release

**Comment by cstevenson1** [comment]
Still unable to back date an inspection. I created and saved an inspection with an Inspection Date of 1/11/2016 but when I went back to the list of list of inspections, it had changed the date to the current date (5/6/2016).

![image](https://cloud.githubusercontent.com/assets/16919898/15080621/1b46de3c-138d-11e6-862c-a240eccae020.png)

![image](https://cloud.githubusercontent.com/assets/16919898/15080711/741c1b26-138d-11e6-8a70-9562af43c682.png)

![image](https://cloud.githubusercontent.com/assets/16919898/15080763/a861a31a-138d-11e6-8c2f-d1e5e6608e5a.png)

**Comment by kanglu666** [comment]
fixed, ready for testing in version 1.1 release

**Comment by cstevenson1** [comment]
Issue has been resolved for structure inspections but does not work for pipe inspections. Inspection date in the list of historical inspections does not reflect the inspection date that was selected in the pipe inspection if it was a backdated date.

![image](https://cloud.githubusercontent.com/assets/16919898/16764292/45068d88-47fb-11e6-95a9-ca88492b5a05.png)

![image](https://cloud.githubusercontent.com/assets/16919898/16764318/5ce91bd2-47fb-11e6-8736-fb7afb642841.png)

**Comment by kanglu666** [comment]
updated, ready for testing in version 1.3 release
